#what would you like to call it

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # naming the deployment
spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 services
    # create a replica set of this with instances/pods
  replicas: 3
    # template to use it's label for k8 service
  template:
    metadata:
      labels:
        app: nginx # This label connects to the service or any other k8 components
    spec:
      containers:
      - name: nginx
        image: ahmedmujtba/docker-profile-project:latest
        ports:
        - containerPort: 80
