apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc # naming the deployment
  namespace: default # sre , not needed unless in production, keeps things separated
spec:
  ports:
  - protocol: TCP
    nodePort: 30005 # range is 30000-32768
    port: 3000
    # port mapping

    targetPort: 3000
  selector:
    app: sparta-app # look for this label to match with k8 services

  type: NodePort


